# Generated by Django 4.2.1 on 2023-06-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_post_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
    ]
