# Generated by Django 4.2.1 on 2023-06-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_post_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
